### ISSUE TITLE
Messages height set as 0

### ISSUE THREAD

**Issue by aitorres** [radiac/django-conversate#1]
I downloaded and installed this package, but after accessing a room's page, I could not read any of the sent messages even though I could confirm they were being sent and stored. 

After checking the css files, I realized the height property of the messages container is set at 0. 

I tried cloning this repository and running the included example Django project, but it was set as 0 there also. 

In both apps, there was no way of looking at the messages due to this fact.

I don't know if I'm not configuring it properly, or if this is a mistake. If it is, I could make a pull request fixing it (it's a one-liner, of course).

Thanks for reading!

**Comment by radiac** [comment]
Thanks for flagging this! If I remember correctly it's intentionally set to 0 to start it small and allow flex to grow it as necessary. I'll double check that and add a comment to explain it in the future.

I think the problem is in the `base.html` and missing instructions about how to style the root containers. The standard styles do expect to be in a container which is at the full height of the screen. With the default root template, it should expand to the height of `div.cnv_con`, but there are no instructions for how to style that or its parent container.

I'll go through and test it further and update the instructions and example when I get a chance, but in the meantime here's a simplified version of what I've got it working with on my own site, in the hope it will point you in the right direction:

This is  `myproject/templates/conversate/base.html` which is overriding conversate's default `base.html`:

```html
<html>
  <body class="full-height">
    <header>...</header>
    {% block conversate_content %}{% endblock %}
  </body>
</html>
```

I do this to avoid needing the extra `div.cnv_con`. The room's root level `section.cnv_container` then pops in at the same level as the `<header>`. You should be able to achieve the same by styling `div.cnv_con` to be the full height of the screen, but I've just copied what I've got to make sure I'm giving you something that actually works.

My styles are then:

```scss
body.full-height {
    height: 100vh;
    overflow: hidden;

    display: flex;
    flex-flow: column nowrap;

    header {
        flex: 0 0 auto;
    }

    section {
        flex: 1 0 auto;
    }
}
```

This sets the body to take up the full screen, makes the header a fixed height, and tells the `section.cnv_container` to grow to the remaining height.

Hope this gets you going until I can take a more detailed look and get a fix out.
